// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/tree/entry.go
//
// Generated by this command:
//
//	mockgen -package=mockTreeEntry -source=pkg/tree/entry.go -destination=./mocks/mocktreeentry/entry.go
//

// Package mockTreeEntry is a generated GoMock package.
package mockTreeEntry

import (
	context "context"
	reflect "reflect"

	etree "github.com/beevik/etree"
	config "github.com/sdcio/data-server/pkg/config"
	tree "github.com/sdcio/data-server/pkg/tree"
	importer "github.com/sdcio/data-server/pkg/tree/importer"
	types "github.com/sdcio/data-server/pkg/tree/types"
	sdcpb "github.com/sdcio/sdc-protos/sdcpb"
	tree_persist "github.com/sdcio/sdc-protos/tree_persist"
	gomock "go.uber.org/mock/gomock"
)

// MockEntry is a mock of Entry interface.
type MockEntry struct {
	ctrl     *gomock.Controller
	recorder *MockEntryMockRecorder
	isgomock struct{}
}

// MockEntryMockRecorder is the mock recorder for MockEntry.
type MockEntryMockRecorder struct {
	mock *MockEntry
}

// NewMockEntry creates a new mock instance.
func NewMockEntry(ctrl *gomock.Controller) *MockEntry {
	mock := &MockEntry{ctrl: ctrl}
	mock.recorder = &MockEntryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntry) EXPECT() *MockEntryMockRecorder {
	return m.recorder
}

// AddUpdateRecursive mocks base method.
func (m *MockEntry) AddUpdateRecursive(ctx context.Context, relativePath *sdcpb.Path, u *types.Update, flags *types.UpdateInsertFlags) (tree.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUpdateRecursive", ctx, relativePath, u, flags)
	ret0, _ := ret[0].(tree.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddUpdateRecursive indicates an expected call of AddUpdateRecursive.
func (mr *MockEntryMockRecorder) AddUpdateRecursive(ctx, relativePath, u, flags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUpdateRecursive", reflect.TypeOf((*MockEntry)(nil).AddUpdateRecursive), ctx, relativePath, u, flags)
}

// BreadthSearch mocks base method.
func (m *MockEntry) BreadthSearch(ctx context.Context, path *sdcpb.Path) ([]tree.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BreadthSearch", ctx, path)
	ret0, _ := ret[0].([]tree.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BreadthSearch indicates an expected call of BreadthSearch.
func (mr *MockEntryMockRecorder) BreadthSearch(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BreadthSearch", reflect.TypeOf((*MockEntry)(nil).BreadthSearch), ctx, path)
}

// DeepCopy mocks base method.
func (m *MockEntry) DeepCopy(tc *tree.TreeContext, parent tree.Entry) (tree.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeepCopy", tc, parent)
	ret0, _ := ret[0].(tree.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeepCopy indicates an expected call of DeepCopy.
func (mr *MockEntryMockRecorder) DeepCopy(tc, parent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeepCopy", reflect.TypeOf((*MockEntry)(nil).DeepCopy), tc, parent)
}

// DeleteBranch mocks base method.
func (m *MockEntry) DeleteBranch(ctx context.Context, path *sdcpb.Path, owner string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBranch", ctx, path, owner)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBranch indicates an expected call of DeleteBranch.
func (mr *MockEntryMockRecorder) DeleteBranch(ctx, path, owner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBranch", reflect.TypeOf((*MockEntry)(nil).DeleteBranch), ctx, path, owner)
}

// FilterChilds mocks base method.
func (m *MockEntry) FilterChilds(keys map[string]string) ([]tree.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterChilds", keys)
	ret0, _ := ret[0].([]tree.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterChilds indicates an expected call of FilterChilds.
func (mr *MockEntryMockRecorder) FilterChilds(keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterChilds", reflect.TypeOf((*MockEntry)(nil).FilterChilds), keys)
}

// FinishInsertionPhase mocks base method.
func (m *MockEntry) FinishInsertionPhase(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinishInsertionPhase", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// FinishInsertionPhase indicates an expected call of FinishInsertionPhase.
func (mr *MockEntryMockRecorder) FinishInsertionPhase(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinishInsertionPhase", reflect.TypeOf((*MockEntry)(nil).FinishInsertionPhase), ctx)
}

// GetByOwner mocks base method.
func (m *MockEntry) GetByOwner(owner string, result []*tree.LeafEntry) tree.LeafVariantSlice {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOwner", owner, result)
	ret0, _ := ret[0].(tree.LeafVariantSlice)
	return ret0
}

// GetByOwner indicates an expected call of GetByOwner.
func (mr *MockEntryMockRecorder) GetByOwner(owner, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOwner", reflect.TypeOf((*MockEntry)(nil).GetByOwner), owner, result)
}

// GetChild mocks base method.
func (m *MockEntry) GetChild(name string) (tree.Entry, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChild", name)
	ret0, _ := ret[0].(tree.Entry)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetChild indicates an expected call of GetChild.
func (mr *MockEntryMockRecorder) GetChild(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChild", reflect.TypeOf((*MockEntry)(nil).GetChild), name)
}

// GetChilds mocks base method.
func (m *MockEntry) GetChilds(arg0 tree.DescendMethod) tree.EntryMap {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChilds", arg0)
	ret0, _ := ret[0].(tree.EntryMap)
	return ret0
}

// GetChilds indicates an expected call of GetChilds.
func (mr *MockEntryMockRecorder) GetChilds(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChilds", reflect.TypeOf((*MockEntry)(nil).GetChilds), arg0)
}

// GetDeletes mocks base method.
func (m *MockEntry) GetDeletes(entries []types.DeleteEntry, aggregatePaths bool) ([]types.DeleteEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeletes", entries, aggregatePaths)
	ret0, _ := ret[0].([]types.DeleteEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeletes indicates an expected call of GetDeletes.
func (mr *MockEntryMockRecorder) GetDeletes(entries, aggregatePaths any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeletes", reflect.TypeOf((*MockEntry)(nil).GetDeletes), entries, aggregatePaths)
}

// GetDeviations mocks base method.
func (m *MockEntry) GetDeviations(ctx context.Context, ch chan<- *types.DeviationEntry, activeCase bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetDeviations", ctx, ch, activeCase)
}

// GetDeviations indicates an expected call of GetDeviations.
func (mr *MockEntryMockRecorder) GetDeviations(ctx, ch, activeCase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviations", reflect.TypeOf((*MockEntry)(nil).GetDeviations), ctx, ch, activeCase)
}

// GetFirstAncestorWithSchema mocks base method.
func (m *MockEntry) GetFirstAncestorWithSchema() (tree.Entry, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFirstAncestorWithSchema")
	ret0, _ := ret[0].(tree.Entry)
	ret1, _ := ret[1].(int)
	return ret0, ret1
}

// GetFirstAncestorWithSchema indicates an expected call of GetFirstAncestorWithSchema.
func (mr *MockEntryMockRecorder) GetFirstAncestorWithSchema() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFirstAncestorWithSchema", reflect.TypeOf((*MockEntry)(nil).GetFirstAncestorWithSchema))
}

// GetHighestPrecedence mocks base method.
func (m *MockEntry) GetHighestPrecedence(result tree.LeafVariantSlice, onlyNewOrUpdated, includeDefaults, includeExplicitDelete bool) tree.LeafVariantSlice {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHighestPrecedence", result, onlyNewOrUpdated, includeDefaults, includeExplicitDelete)
	ret0, _ := ret[0].(tree.LeafVariantSlice)
	return ret0
}

// GetHighestPrecedence indicates an expected call of GetHighestPrecedence.
func (mr *MockEntryMockRecorder) GetHighestPrecedence(result, onlyNewOrUpdated, includeDefaults, includeExplicitDelete any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHighestPrecedence", reflect.TypeOf((*MockEntry)(nil).GetHighestPrecedence), result, onlyNewOrUpdated, includeDefaults, includeExplicitDelete)
}

// GetLeafVariantEntries mocks base method.
func (m *MockEntry) GetLeafVariantEntries() tree.LeafVariantEntries {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLeafVariantEntries")
	ret0, _ := ret[0].(tree.LeafVariantEntries)
	return ret0
}

// GetLeafVariantEntries indicates an expected call of GetLeafVariantEntries.
func (mr *MockEntryMockRecorder) GetLeafVariantEntries() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLeafVariantEntries", reflect.TypeOf((*MockEntry)(nil).GetLeafVariantEntries))
}

// GetLevel mocks base method.
func (m *MockEntry) GetLevel() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLevel")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetLevel indicates an expected call of GetLevel.
func (mr *MockEntryMockRecorder) GetLevel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLevel", reflect.TypeOf((*MockEntry)(nil).GetLevel))
}

// GetListChilds mocks base method.
func (m *MockEntry) GetListChilds() ([]tree.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListChilds")
	ret0, _ := ret[0].([]tree.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListChilds indicates an expected call of GetListChilds.
func (mr *MockEntryMockRecorder) GetListChilds() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListChilds", reflect.TypeOf((*MockEntry)(nil).GetListChilds))
}

// GetParent mocks base method.
func (m *MockEntry) GetParent() tree.Entry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParent")
	ret0, _ := ret[0].(tree.Entry)
	return ret0
}

// GetParent indicates an expected call of GetParent.
func (mr *MockEntryMockRecorder) GetParent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParent", reflect.TypeOf((*MockEntry)(nil).GetParent))
}

// GetRoot mocks base method.
func (m *MockEntry) GetRoot() tree.Entry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoot")
	ret0, _ := ret[0].(tree.Entry)
	return ret0
}

// GetRoot indicates an expected call of GetRoot.
func (mr *MockEntryMockRecorder) GetRoot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoot", reflect.TypeOf((*MockEntry)(nil).GetRoot))
}

// GetRootBasedEntryChain mocks base method.
func (m *MockEntry) GetRootBasedEntryChain() []tree.Entry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRootBasedEntryChain")
	ret0, _ := ret[0].([]tree.Entry)
	return ret0
}

// GetRootBasedEntryChain indicates an expected call of GetRootBasedEntryChain.
func (mr *MockEntryMockRecorder) GetRootBasedEntryChain() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRootBasedEntryChain", reflect.TypeOf((*MockEntry)(nil).GetRootBasedEntryChain))
}

// GetSchema mocks base method.
func (m *MockEntry) GetSchema() *sdcpb.SchemaElem {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSchema")
	ret0, _ := ret[0].(*sdcpb.SchemaElem)
	return ret0
}

// GetSchema indicates an expected call of GetSchema.
func (mr *MockEntryMockRecorder) GetSchema() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSchema", reflect.TypeOf((*MockEntry)(nil).GetSchema))
}

// GetSchemaKeys mocks base method.
func (m *MockEntry) GetSchemaKeys() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSchemaKeys")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetSchemaKeys indicates an expected call of GetSchemaKeys.
func (mr *MockEntryMockRecorder) GetSchemaKeys() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSchemaKeys", reflect.TypeOf((*MockEntry)(nil).GetSchemaKeys))
}

// HoldsLeafvariants mocks base method.
func (m *MockEntry) HoldsLeafvariants() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HoldsLeafvariants")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HoldsLeafvariants indicates an expected call of HoldsLeafvariants.
func (mr *MockEntryMockRecorder) HoldsLeafvariants() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HoldsLeafvariants", reflect.TypeOf((*MockEntry)(nil).HoldsLeafvariants))
}

// ImportConfig mocks base method.
func (m *MockEntry) ImportConfig(ctx context.Context, arg1 importer.ImportConfigAdapterElement, intentName string, intentPrio int32, flags *types.UpdateInsertFlags) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportConfig", ctx, arg1, intentName, intentPrio, flags)
	ret0, _ := ret[0].(error)
	return ret0
}

// ImportConfig indicates an expected call of ImportConfig.
func (mr *MockEntryMockRecorder) ImportConfig(ctx, arg1, intentName, intentPrio, flags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportConfig", reflect.TypeOf((*MockEntry)(nil).ImportConfig), ctx, arg1, intentName, intentPrio, flags)
}

// IsRoot mocks base method.
func (m *MockEntry) IsRoot() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRoot")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsRoot indicates an expected call of IsRoot.
func (mr *MockEntryMockRecorder) IsRoot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRoot", reflect.TypeOf((*MockEntry)(nil).IsRoot))
}

// NavigateLeafRef mocks base method.
func (m *MockEntry) NavigateLeafRef(ctx context.Context) ([]tree.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NavigateLeafRef", ctx)
	ret0, _ := ret[0].([]tree.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NavigateLeafRef indicates an expected call of NavigateLeafRef.
func (mr *MockEntryMockRecorder) NavigateLeafRef(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NavigateLeafRef", reflect.TypeOf((*MockEntry)(nil).NavigateLeafRef), ctx)
}

// NavigateSdcpbPath mocks base method.
func (m *MockEntry) NavigateSdcpbPath(ctx context.Context, path *sdcpb.Path) (tree.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NavigateSdcpbPath", ctx, path)
	ret0, _ := ret[0].(tree.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NavigateSdcpbPath indicates an expected call of NavigateSdcpbPath.
func (mr *MockEntryMockRecorder) NavigateSdcpbPath(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NavigateSdcpbPath", reflect.TypeOf((*MockEntry)(nil).NavigateSdcpbPath), ctx, path)
}

// PathName mocks base method.
func (m *MockEntry) PathName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PathName")
	ret0, _ := ret[0].(string)
	return ret0
}

// PathName indicates an expected call of PathName.
func (mr *MockEntryMockRecorder) PathName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PathName", reflect.TypeOf((*MockEntry)(nil).PathName))
}

// SdcpbPath mocks base method.
func (m *MockEntry) SdcpbPath() *sdcpb.Path {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SdcpbPath")
	ret0, _ := ret[0].(*sdcpb.Path)
	return ret0
}

// SdcpbPath indicates an expected call of SdcpbPath.
func (mr *MockEntryMockRecorder) SdcpbPath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SdcpbPath", reflect.TypeOf((*MockEntry)(nil).SdcpbPath))
}

// StringIndent mocks base method.
func (m *MockEntry) StringIndent(result []string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StringIndent", result)
	ret0, _ := ret[0].([]string)
	return ret0
}

// StringIndent indicates an expected call of StringIndent.
func (mr *MockEntryMockRecorder) StringIndent(result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StringIndent", reflect.TypeOf((*MockEntry)(nil).StringIndent), result)
}

// ToJson mocks base method.
func (m *MockEntry) ToJson(onlyNewOrUpdated bool) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToJson", onlyNewOrUpdated)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToJson indicates an expected call of ToJson.
func (mr *MockEntryMockRecorder) ToJson(onlyNewOrUpdated any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToJson", reflect.TypeOf((*MockEntry)(nil).ToJson), onlyNewOrUpdated)
}

// ToJsonIETF mocks base method.
func (m *MockEntry) ToJsonIETF(onlyNewOrUpdated bool) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToJsonIETF", onlyNewOrUpdated)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToJsonIETF indicates an expected call of ToJsonIETF.
func (mr *MockEntryMockRecorder) ToJsonIETF(onlyNewOrUpdated any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToJsonIETF", reflect.TypeOf((*MockEntry)(nil).ToJsonIETF), onlyNewOrUpdated)
}

// ToXML mocks base method.
func (m *MockEntry) ToXML(onlyNewOrUpdated, honorNamespace, operationWithNamespace, useOperationRemove bool) (*etree.Document, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToXML", onlyNewOrUpdated, honorNamespace, operationWithNamespace, useOperationRemove)
	ret0, _ := ret[0].(*etree.Document)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToXML indicates an expected call of ToXML.
func (mr *MockEntryMockRecorder) ToXML(onlyNewOrUpdated, honorNamespace, operationWithNamespace, useOperationRemove any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToXML", reflect.TypeOf((*MockEntry)(nil).ToXML), onlyNewOrUpdated, honorNamespace, operationWithNamespace, useOperationRemove)
}

// TreeExport mocks base method.
func (m *MockEntry) TreeExport(owner string) ([]*tree_persist.TreeElement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TreeExport", owner)
	ret0, _ := ret[0].([]*tree_persist.TreeElement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TreeExport indicates an expected call of TreeExport.
func (mr *MockEntryMockRecorder) TreeExport(owner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TreeExport", reflect.TypeOf((*MockEntry)(nil).TreeExport), owner)
}

// ValidateLevel mocks base method.
func (m *MockEntry) ValidateLevel(ctx context.Context, resultChan chan<- *types.ValidationResultEntry, stats *types.ValidationStats, vCfg *config.Validation) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ValidateLevel", ctx, resultChan, stats, vCfg)
}

// ValidateLevel indicates an expected call of ValidateLevel.
func (mr *MockEntryMockRecorder) ValidateLevel(ctx, resultChan, stats, vCfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateLevel", reflect.TypeOf((*MockEntry)(nil).ValidateLevel), ctx, resultChan, stats, vCfg)
}

// Walk mocks base method.
func (m *MockEntry) Walk(ctx context.Context, v tree.EntryVisitor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Walk", ctx, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Walk indicates an expected call of Walk.
func (mr *MockEntryMockRecorder) Walk(ctx, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Walk", reflect.TypeOf((*MockEntry)(nil).Walk), ctx, v)
}

// addChild mocks base method.
func (m *MockEntry) addChild(arg0 context.Context, arg1 tree.Entry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "addChild", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// addChild indicates an expected call of addChild.
func (mr *MockEntryMockRecorder) addChild(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "addChild", reflect.TypeOf((*MockEntry)(nil).addChild), arg0, arg1)
}

// addUpdateRecursiveInternal mocks base method.
func (m *MockEntry) addUpdateRecursiveInternal(ctx context.Context, path *sdcpb.Path, idx int, u *types.Update, flags *types.UpdateInsertFlags) (tree.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "addUpdateRecursiveInternal", ctx, path, idx, u, flags)
	ret0, _ := ret[0].(tree.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// addUpdateRecursiveInternal indicates an expected call of addUpdateRecursiveInternal.
func (mr *MockEntryMockRecorder) addUpdateRecursiveInternal(ctx, path, idx, u, flags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "addUpdateRecursiveInternal", reflect.TypeOf((*MockEntry)(nil).addUpdateRecursiveInternal), ctx, path, idx, u, flags)
}

// canDelete mocks base method.
func (m *MockEntry) canDelete() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "canDelete")
	ret0, _ := ret[0].(bool)
	return ret0
}

// canDelete indicates an expected call of canDelete.
func (mr *MockEntryMockRecorder) canDelete() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "canDelete", reflect.TypeOf((*MockEntry)(nil).canDelete))
}

// canDeleteBranch mocks base method.
func (m *MockEntry) canDeleteBranch(keepDefault bool) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "canDeleteBranch", keepDefault)
	ret0, _ := ret[0].(bool)
	return ret0
}

// canDeleteBranch indicates an expected call of canDeleteBranch.
func (mr *MockEntryMockRecorder) canDeleteBranch(keepDefault any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "canDeleteBranch", reflect.TypeOf((*MockEntry)(nil).canDeleteBranch), keepDefault)
}

// deleteCanDeleteChilds mocks base method.
func (m *MockEntry) deleteCanDeleteChilds(keepDefault bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "deleteCanDeleteChilds", keepDefault)
}

// deleteCanDeleteChilds indicates an expected call of deleteCanDeleteChilds.
func (mr *MockEntryMockRecorder) deleteCanDeleteChilds(keepDefault any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "deleteCanDeleteChilds", reflect.TypeOf((*MockEntry)(nil).deleteCanDeleteChilds), keepDefault)
}

// getHighestPrecedenceLeafValue mocks base method.
func (m *MockEntry) getHighestPrecedenceLeafValue(arg0 context.Context) (*tree.LeafEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getHighestPrecedenceLeafValue", arg0)
	ret0, _ := ret[0].(*tree.LeafEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getHighestPrecedenceLeafValue indicates an expected call of getHighestPrecedenceLeafValue.
func (mr *MockEntryMockRecorder) getHighestPrecedenceLeafValue(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getHighestPrecedenceLeafValue", reflect.TypeOf((*MockEntry)(nil).getHighestPrecedenceLeafValue), arg0)
}

// getHighestPrecedenceValueOfBranch mocks base method.
func (m *MockEntry) getHighestPrecedenceValueOfBranch(filter tree.HighestPrecedenceFilter) int32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getHighestPrecedenceValueOfBranch", filter)
	ret0, _ := ret[0].(int32)
	return ret0
}

// getHighestPrecedenceValueOfBranch indicates an expected call of getHighestPrecedenceValueOfBranch.
func (mr *MockEntryMockRecorder) getHighestPrecedenceValueOfBranch(filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getHighestPrecedenceValueOfBranch", reflect.TypeOf((*MockEntry)(nil).getHighestPrecedenceValueOfBranch), filter)
}

// getOrCreateChilds mocks base method.
func (m *MockEntry) getOrCreateChilds(ctx context.Context, path *sdcpb.Path) (tree.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getOrCreateChilds", ctx, path)
	ret0, _ := ret[0].(tree.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getOrCreateChilds indicates an expected call of getOrCreateChilds.
func (mr *MockEntryMockRecorder) getOrCreateChilds(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getOrCreateChilds", reflect.TypeOf((*MockEntry)(nil).getOrCreateChilds), ctx, path)
}

// remainsToExist mocks base method.
func (m *MockEntry) remainsToExist() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "remainsToExist")
	ret0, _ := ret[0].(bool)
	return ret0
}

// remainsToExist indicates an expected call of remainsToExist.
func (mr *MockEntryMockRecorder) remainsToExist() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "remainsToExist", reflect.TypeOf((*MockEntry)(nil).remainsToExist))
}

// shouldDelete mocks base method.
func (m *MockEntry) shouldDelete() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "shouldDelete")
	ret0, _ := ret[0].(bool)
	return ret0
}

// shouldDelete indicates an expected call of shouldDelete.
func (mr *MockEntryMockRecorder) shouldDelete() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "shouldDelete", reflect.TypeOf((*MockEntry)(nil).shouldDelete))
}

// toJsonInternal mocks base method.
func (m *MockEntry) toJsonInternal(onlyNewOrUpdated, ietf bool) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "toJsonInternal", onlyNewOrUpdated, ietf)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// toJsonInternal indicates an expected call of toJsonInternal.
func (mr *MockEntryMockRecorder) toJsonInternal(onlyNewOrUpdated, ietf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "toJsonInternal", reflect.TypeOf((*MockEntry)(nil).toJsonInternal), onlyNewOrUpdated, ietf)
}

// toXmlInternal mocks base method.
func (m *MockEntry) toXmlInternal(parent *etree.Element, onlyNewOrUpdated, honorNamespace, operationWithNamespace, useOperationRemove bool) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "toXmlInternal", parent, onlyNewOrUpdated, honorNamespace, operationWithNamespace, useOperationRemove)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// toXmlInternal indicates an expected call of toXmlInternal.
func (mr *MockEntryMockRecorder) toXmlInternal(parent, onlyNewOrUpdated, honorNamespace, operationWithNamespace, useOperationRemove any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "toXmlInternal", reflect.TypeOf((*MockEntry)(nil).toXmlInternal), parent, onlyNewOrUpdated, honorNamespace, operationWithNamespace, useOperationRemove)
}

// validateMandatory mocks base method.
func (m *MockEntry) validateMandatory(ctx context.Context, resultChan chan<- *types.ValidationResultEntry, stats *types.ValidationStats) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "validateMandatory", ctx, resultChan, stats)
}

// validateMandatory indicates an expected call of validateMandatory.
func (mr *MockEntryMockRecorder) validateMandatory(ctx, resultChan, stats any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "validateMandatory", reflect.TypeOf((*MockEntry)(nil).validateMandatory), ctx, resultChan, stats)
}

// validateMandatoryWithKeys mocks base method.
func (m *MockEntry) validateMandatoryWithKeys(ctx context.Context, level int, attributes []string, choiceName string, resultChan chan<- *types.ValidationResultEntry) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "validateMandatoryWithKeys", ctx, level, attributes, choiceName, resultChan)
}

// validateMandatoryWithKeys indicates an expected call of validateMandatoryWithKeys.
func (mr *MockEntryMockRecorder) validateMandatoryWithKeys(ctx, level, attributes, choiceName, resultChan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "validateMandatoryWithKeys", reflect.TypeOf((*MockEntry)(nil).validateMandatoryWithKeys), ctx, level, attributes, choiceName, resultChan)
}

// MockEntryVisitor is a mock of EntryVisitor interface.
type MockEntryVisitor struct {
	ctrl     *gomock.Controller
	recorder *MockEntryVisitorMockRecorder
	isgomock struct{}
}

// MockEntryVisitorMockRecorder is the mock recorder for MockEntryVisitor.
type MockEntryVisitorMockRecorder struct {
	mock *MockEntryVisitor
}

// NewMockEntryVisitor creates a new mock instance.
func NewMockEntryVisitor(ctrl *gomock.Controller) *MockEntryVisitor {
	mock := &MockEntryVisitor{ctrl: ctrl}
	mock.recorder = &MockEntryVisitorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntryVisitor) EXPECT() *MockEntryVisitorMockRecorder {
	return m.recorder
}

// DescendMethod mocks base method.
func (m *MockEntryVisitor) DescendMethod() tree.DescendMethod {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescendMethod")
	ret0, _ := ret[0].(tree.DescendMethod)
	return ret0
}

// DescendMethod indicates an expected call of DescendMethod.
func (mr *MockEntryVisitorMockRecorder) DescendMethod() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescendMethod", reflect.TypeOf((*MockEntryVisitor)(nil).DescendMethod))
}

// Up mocks base method.
func (m *MockEntryVisitor) Up() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Up")
}

// Up indicates an expected call of Up.
func (mr *MockEntryVisitorMockRecorder) Up() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Up", reflect.TypeOf((*MockEntryVisitor)(nil).Up))
}

// Visit mocks base method.
func (m *MockEntryVisitor) Visit(ctx context.Context, e tree.Entry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Visit", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// Visit indicates an expected call of Visit.
func (mr *MockEntryVisitorMockRecorder) Visit(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Visit", reflect.TypeOf((*MockEntryVisitor)(nil).Visit), ctx, e)
}

// MockLeafVariantEntry is a mock of LeafVariantEntry interface.
type MockLeafVariantEntry struct {
	ctrl     *gomock.Controller
	recorder *MockLeafVariantEntryMockRecorder
	isgomock struct{}
}

// MockLeafVariantEntryMockRecorder is the mock recorder for MockLeafVariantEntry.
type MockLeafVariantEntryMockRecorder struct {
	mock *MockLeafVariantEntry
}

// NewMockLeafVariantEntry creates a new mock instance.
func NewMockLeafVariantEntry(ctrl *gomock.Controller) *MockLeafVariantEntry {
	mock := &MockLeafVariantEntry{ctrl: ctrl}
	mock.recorder = &MockLeafVariantEntryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLeafVariantEntry) EXPECT() *MockLeafVariantEntryMockRecorder {
	return m.recorder
}

// GetEntry mocks base method.
func (m *MockLeafVariantEntry) GetEntry() tree.Entry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntry")
	ret0, _ := ret[0].(tree.Entry)
	return ret0
}

// GetEntry indicates an expected call of GetEntry.
func (mr *MockLeafVariantEntryMockRecorder) GetEntry() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntry", reflect.TypeOf((*MockLeafVariantEntry)(nil).GetEntry))
}

// MarkDelete mocks base method.
func (m *MockLeafVariantEntry) MarkDelete(onlyIntended bool) *tree.LeafEntry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkDelete", onlyIntended)
	ret0, _ := ret[0].(*tree.LeafEntry)
	return ret0
}

// MarkDelete indicates an expected call of MarkDelete.
func (mr *MockLeafVariantEntryMockRecorder) MarkDelete(onlyIntended any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkDelete", reflect.TypeOf((*MockLeafVariantEntry)(nil).MarkDelete), onlyIntended)
}

// String mocks base method.
func (m *MockLeafVariantEntry) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockLeafVariantEntryMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockLeafVariantEntry)(nil).String))
}

// MockLeafVariantEntries is a mock of LeafVariantEntries interface.
type MockLeafVariantEntries struct {
	ctrl     *gomock.Controller
	recorder *MockLeafVariantEntriesMockRecorder
	isgomock struct{}
}

// MockLeafVariantEntriesMockRecorder is the mock recorder for MockLeafVariantEntries.
type MockLeafVariantEntriesMockRecorder struct {
	mock *MockLeafVariantEntries
}

// NewMockLeafVariantEntries creates a new mock instance.
func NewMockLeafVariantEntries(ctrl *gomock.Controller) *MockLeafVariantEntries {
	mock := &MockLeafVariantEntries{ctrl: ctrl}
	mock.recorder = &MockLeafVariantEntriesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLeafVariantEntries) EXPECT() *MockLeafVariantEntriesMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockLeafVariantEntries) Add(l *tree.LeafEntry) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Add", l)
}

// Add indicates an expected call of Add.
func (mr *MockLeafVariantEntriesMockRecorder) Add(l any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockLeafVariantEntries)(nil).Add), l)
}

// AddExplicitDeleteEntry mocks base method.
func (m *MockLeafVariantEntries) AddExplicitDeleteEntry(owner string, priority int32) *tree.LeafEntry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddExplicitDeleteEntry", owner, priority)
	ret0, _ := ret[0].(*tree.LeafEntry)
	return ret0
}

// AddExplicitDeleteEntry indicates an expected call of AddExplicitDeleteEntry.
func (mr *MockLeafVariantEntriesMockRecorder) AddExplicitDeleteEntry(owner, priority any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddExplicitDeleteEntry", reflect.TypeOf((*MockLeafVariantEntries)(nil).AddExplicitDeleteEntry), owner, priority)
}

// DeleteByOwner mocks base method.
func (m *MockLeafVariantEntries) DeleteByOwner(owner string) *tree.LeafEntry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByOwner", owner)
	ret0, _ := ret[0].(*tree.LeafEntry)
	return ret0
}

// DeleteByOwner indicates an expected call of DeleteByOwner.
func (mr *MockLeafVariantEntriesMockRecorder) DeleteByOwner(owner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByOwner", reflect.TypeOf((*MockLeafVariantEntries)(nil).DeleteByOwner), owner)
}

// GetByOwner mocks base method.
func (m *MockLeafVariantEntries) GetByOwner(owner string) *tree.LeafEntry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOwner", owner)
	ret0, _ := ret[0].(*tree.LeafEntry)
	return ret0
}

// GetByOwner indicates an expected call of GetByOwner.
func (mr *MockLeafVariantEntriesMockRecorder) GetByOwner(owner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOwner", reflect.TypeOf((*MockLeafVariantEntries)(nil).GetByOwner), owner)
}

// GetHighestPrecedence mocks base method.
func (m *MockLeafVariantEntries) GetHighestPrecedence(onlyNewOrUpdated, includeDefaults, includeExplicitDeletes bool) *tree.LeafEntry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHighestPrecedence", onlyNewOrUpdated, includeDefaults, includeExplicitDeletes)
	ret0, _ := ret[0].(*tree.LeafEntry)
	return ret0
}

// GetHighestPrecedence indicates an expected call of GetHighestPrecedence.
func (mr *MockLeafVariantEntriesMockRecorder) GetHighestPrecedence(onlyNewOrUpdated, includeDefaults, includeExplicitDeletes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHighestPrecedence", reflect.TypeOf((*MockLeafVariantEntries)(nil).GetHighestPrecedence), onlyNewOrUpdated, includeDefaults, includeExplicitDeletes)
}

// GetRunning mocks base method.
func (m *MockLeafVariantEntries) GetRunning() *tree.LeafEntry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRunning")
	ret0, _ := ret[0].(*tree.LeafEntry)
	return ret0
}

// GetRunning indicates an expected call of GetRunning.
func (mr *MockLeafVariantEntriesMockRecorder) GetRunning() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRunning", reflect.TypeOf((*MockLeafVariantEntries)(nil).GetRunning))
}

// Length mocks base method.
func (m *MockLeafVariantEntries) Length() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Length")
	ret0, _ := ret[0].(int)
	return ret0
}

// Length indicates an expected call of Length.
func (mr *MockLeafVariantEntriesMockRecorder) Length() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Length", reflect.TypeOf((*MockLeafVariantEntries)(nil).Length))
}

// MarkOwnerForDeletion mocks base method.
func (m *MockLeafVariantEntries) MarkOwnerForDeletion(owner string, onlyIntended bool) *tree.LeafEntry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkOwnerForDeletion", owner, onlyIntended)
	ret0, _ := ret[0].(*tree.LeafEntry)
	return ret0
}

// MarkOwnerForDeletion indicates an expected call of MarkOwnerForDeletion.
func (mr *MockLeafVariantEntriesMockRecorder) MarkOwnerForDeletion(owner, onlyIntended any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkOwnerForDeletion", reflect.TypeOf((*MockLeafVariantEntries)(nil).MarkOwnerForDeletion), owner, onlyIntended)
}

// RemoveDeletedByOwner mocks base method.
func (m *MockLeafVariantEntries) RemoveDeletedByOwner(owner string) *tree.LeafEntry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveDeletedByOwner", owner)
	ret0, _ := ret[0].(*tree.LeafEntry)
	return ret0
}

// RemoveDeletedByOwner indicates an expected call of RemoveDeletedByOwner.
func (mr *MockLeafVariantEntriesMockRecorder) RemoveDeletedByOwner(owner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveDeletedByOwner", reflect.TypeOf((*MockLeafVariantEntries)(nil).RemoveDeletedByOwner), owner)
}

// ResetFlags mocks base method.
func (m *MockLeafVariantEntries) ResetFlags(deleteFlag, newFlag, updatedFlag bool) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetFlags", deleteFlag, newFlag, updatedFlag)
	ret0, _ := ret[0].(int)
	return ret0
}

// ResetFlags indicates an expected call of ResetFlags.
func (mr *MockLeafVariantEntriesMockRecorder) ResetFlags(deleteFlag, newFlag, updatedFlag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetFlags", reflect.TypeOf((*MockLeafVariantEntries)(nil).ResetFlags), deleteFlag, newFlag, updatedFlag)
}
