// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/tree/api/sdcpb_path.go
//
// Generated by this command:
//
//	mockgen -package=mocksdcpbpath -source=pkg/tree/api/sdcpb_path.go -destination=./mocks/mocksdcpbpath/sdcpb_path.go
//

// Package mocksdcpbpath is a generated GoMock package.
package mocksdcpbpath

import (
	reflect "reflect"

	sdcpb "github.com/sdcio/sdc-protos/sdcpb"
	gomock "go.uber.org/mock/gomock"
)

// MockSdcpbPath is a mock of SdcpbPath interface.
type MockSdcpbPath struct {
	ctrl     *gomock.Controller
	recorder *MockSdcpbPathMockRecorder
	isgomock struct{}
}

// MockSdcpbPathMockRecorder is the mock recorder for MockSdcpbPath.
type MockSdcpbPathMockRecorder struct {
	mock *MockSdcpbPath
}

// NewMockSdcpbPath creates a new mock instance.
func NewMockSdcpbPath(ctrl *gomock.Controller) *MockSdcpbPath {
	mock := &MockSdcpbPath{ctrl: ctrl}
	mock.recorder = &MockSdcpbPathMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSdcpbPath) EXPECT() *MockSdcpbPathMockRecorder {
	return m.recorder
}

// SdcpbPath mocks base method.
func (m *MockSdcpbPath) SdcpbPath() *sdcpb.Path {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SdcpbPath")
	ret0, _ := ret[0].(*sdcpb.Path)
	return ret0
}

// SdcpbPath indicates an expected call of SdcpbPath.
func (mr *MockSdcpbPathMockRecorder) SdcpbPath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SdcpbPath", reflect.TypeOf((*MockSdcpbPath)(nil).SdcpbPath))
}
