// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/cache/cacheClientBound.go
//
// Generated by this command:
//
//	mockgen -package=mockcacheclient -source=pkg/cache/cacheClientBound.go -destination=./mocks/mockcacheclient/clientbound.go
//

// Package mockcacheclient is a generated GoMock package.
package mockcacheclient

import (
	context "context"
	reflect "reflect"

	tree_persist "github.com/sdcio/sdc-protos/tree_persist"
	gomock "go.uber.org/mock/gomock"
)

// MockCacheClientBound is a mock of CacheClientBound interface.
type MockCacheClientBound struct {
	ctrl     *gomock.Controller
	recorder *MockCacheClientBoundMockRecorder
	isgomock struct{}
}

// MockCacheClientBoundMockRecorder is the mock recorder for MockCacheClientBound.
type MockCacheClientBoundMockRecorder struct {
	mock *MockCacheClientBound
}

// NewMockCacheClientBound creates a new mock instance.
func NewMockCacheClientBound(ctrl *gomock.Controller) *MockCacheClientBound {
	mock := &MockCacheClientBound{ctrl: ctrl}
	mock.recorder = &MockCacheClientBoundMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheClientBound) EXPECT() *MockCacheClientBoundMockRecorder {
	return m.recorder
}

// InstanceClose mocks base method.
func (m *MockCacheClientBound) InstanceClose(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstanceClose", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// InstanceClose indicates an expected call of InstanceClose.
func (mr *MockCacheClientBoundMockRecorder) InstanceClose(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstanceClose", reflect.TypeOf((*MockCacheClientBound)(nil).InstanceClose), ctx)
}

// InstanceCreate mocks base method.
func (m *MockCacheClientBound) InstanceCreate(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstanceCreate", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// InstanceCreate indicates an expected call of InstanceCreate.
func (mr *MockCacheClientBoundMockRecorder) InstanceCreate(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstanceCreate", reflect.TypeOf((*MockCacheClientBound)(nil).InstanceCreate), ctx)
}

// InstanceDelete mocks base method.
func (m *MockCacheClientBound) InstanceDelete(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstanceDelete", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// InstanceDelete indicates an expected call of InstanceDelete.
func (mr *MockCacheClientBoundMockRecorder) InstanceDelete(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstanceDelete", reflect.TypeOf((*MockCacheClientBound)(nil).InstanceDelete), ctx)
}

// InstanceExists mocks base method.
func (m *MockCacheClientBound) InstanceExists(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstanceExists", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// InstanceExists indicates an expected call of InstanceExists.
func (mr *MockCacheClientBoundMockRecorder) InstanceExists(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstanceExists", reflect.TypeOf((*MockCacheClientBound)(nil).InstanceExists), ctx)
}

// IntentDelete mocks base method.
func (m *MockCacheClientBound) IntentDelete(ctx context.Context, intentName string, IgnoreNonExisting bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntentDelete", ctx, intentName, IgnoreNonExisting)
	ret0, _ := ret[0].(error)
	return ret0
}

// IntentDelete indicates an expected call of IntentDelete.
func (mr *MockCacheClientBoundMockRecorder) IntentDelete(ctx, intentName, IgnoreNonExisting any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntentDelete", reflect.TypeOf((*MockCacheClientBound)(nil).IntentDelete), ctx, intentName, IgnoreNonExisting)
}

// IntentExists mocks base method.
func (m *MockCacheClientBound) IntentExists(ctx context.Context, intentName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntentExists", ctx, intentName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IntentExists indicates an expected call of IntentExists.
func (mr *MockCacheClientBoundMockRecorder) IntentExists(ctx, intentName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntentExists", reflect.TypeOf((*MockCacheClientBound)(nil).IntentExists), ctx, intentName)
}

// IntentGet mocks base method.
func (m *MockCacheClientBound) IntentGet(ctx context.Context, intentName string) (*tree_persist.Intent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntentGet", ctx, intentName)
	ret0, _ := ret[0].(*tree_persist.Intent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IntentGet indicates an expected call of IntentGet.
func (mr *MockCacheClientBoundMockRecorder) IntentGet(ctx, intentName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntentGet", reflect.TypeOf((*MockCacheClientBound)(nil).IntentGet), ctx, intentName)
}

// IntentGetAll mocks base method.
func (m *MockCacheClientBound) IntentGetAll(ctx context.Context, excludeIntentNames []string, intentChan chan<- *tree_persist.Intent, errChan chan<- error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IntentGetAll", ctx, excludeIntentNames, intentChan, errChan)
}

// IntentGetAll indicates an expected call of IntentGetAll.
func (mr *MockCacheClientBoundMockRecorder) IntentGetAll(ctx, excludeIntentNames, intentChan, errChan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntentGetAll", reflect.TypeOf((*MockCacheClientBound)(nil).IntentGetAll), ctx, excludeIntentNames, intentChan, errChan)
}

// IntentModify mocks base method.
func (m *MockCacheClientBound) IntentModify(ctx context.Context, intent *tree_persist.Intent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntentModify", ctx, intent)
	ret0, _ := ret[0].(error)
	return ret0
}

// IntentModify indicates an expected call of IntentModify.
func (mr *MockCacheClientBoundMockRecorder) IntentModify(ctx, intent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntentModify", reflect.TypeOf((*MockCacheClientBound)(nil).IntentModify), ctx, intent)
}

// IntentsList mocks base method.
func (m *MockCacheClientBound) IntentsList(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntentsList", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IntentsList indicates an expected call of IntentsList.
func (mr *MockCacheClientBoundMockRecorder) IntentsList(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntentsList", reflect.TypeOf((*MockCacheClientBound)(nil).IntentsList), ctx)
}
