// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sdcio/sdc-protos/config_read (interfaces: ConfigReadServiceClient)
//
// Generated by this command:
//
//	mockgen -package=mockconfigread -destination=./mocks/mockconfigread/client.go github.com/sdcio/sdc-protos/config_read ConfigReadServiceClient
//

// Package mockconfigread is a generated GoMock package.
package mockconfigread

import (
	context "context"
	reflect "reflect"

	config_read "github.com/sdcio/sdc-protos/config_read"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockConfigReadServiceClient is a mock of ConfigReadServiceClient interface.
type MockConfigReadServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockConfigReadServiceClientMockRecorder
	isgomock struct{}
}

// MockConfigReadServiceClientMockRecorder is the mock recorder for MockConfigReadServiceClient.
type MockConfigReadServiceClientMockRecorder struct {
	mock *MockConfigReadServiceClient
}

// NewMockConfigReadServiceClient creates a new mock instance.
func NewMockConfigReadServiceClient(ctrl *gomock.Controller) *MockConfigReadServiceClient {
	mock := &MockConfigReadServiceClient{ctrl: ctrl}
	mock.recorder = &MockConfigReadServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigReadServiceClient) EXPECT() *MockConfigReadServiceClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockConfigReadServiceClient) Get(ctx context.Context, in *config_read.GetConfigRequest, opts ...grpc.CallOption) (*config_read.GetConfigResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*config_read.GetConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockConfigReadServiceClientMockRecorder) Get(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockConfigReadServiceClient)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockConfigReadServiceClient) List(ctx context.Context, in *config_read.ListConfigRequest, opts ...grpc.CallOption) (*config_read.ListConfigResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*config_read.ListConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockConfigReadServiceClientMockRecorder) List(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockConfigReadServiceClient)(nil).List), varargs...)
}
