// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sdcio/sdc-protos/config_read (interfaces: ConfigSnapshotServiceClient)
//
// Generated by this command:
//
//	mockgen -package=mockconfigread -destination=./mocks/mockconfigread/client.go github.com/sdcio/sdc-protos/config_read ConfigSnapshotServiceClient
//

// Package mockconfigread is a generated GoMock package.
package mockconfigread

import (
	context "context"
	reflect "reflect"

	config_read "github.com/sdcio/sdc-protos/config_read"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockConfigSnapshotServiceClient is a mock of ConfigSnapshotServiceClient interface.
type MockConfigSnapshotServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockConfigSnapshotServiceClientMockRecorder
	isgomock struct{}
}

// MockConfigSnapshotServiceClientMockRecorder is the mock recorder for MockConfigSnapshotServiceClient.
type MockConfigSnapshotServiceClientMockRecorder struct {
	mock *MockConfigSnapshotServiceClient
}

// NewMockConfigSnapshotServiceClient creates a new mock instance.
func NewMockConfigSnapshotServiceClient(ctrl *gomock.Controller) *MockConfigSnapshotServiceClient {
	mock := &MockConfigSnapshotServiceClient{ctrl: ctrl}
	mock.recorder = &MockConfigSnapshotServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigSnapshotServiceClient) EXPECT() *MockConfigSnapshotServiceClientMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockConfigSnapshotServiceClient) Delete(ctx context.Context, in *config_read.DeleteConfigRequest, opts ...grpc.CallOption) (*config_read.DeleteConfigResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*config_read.DeleteConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockConfigSnapshotServiceClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockConfigSnapshotServiceClient)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockConfigSnapshotServiceClient) Get(ctx context.Context, in *config_read.GetConfigRequest, opts ...grpc.CallOption) (*config_read.GetConfigResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*config_read.GetConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockConfigSnapshotServiceClientMockRecorder) Get(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockConfigSnapshotServiceClient)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockConfigSnapshotServiceClient) List(ctx context.Context, in *config_read.ListConfigRequest, opts ...grpc.CallOption) (*config_read.ListConfigResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*config_read.ListConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockConfigSnapshotServiceClientMockRecorder) List(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockConfigSnapshotServiceClient)(nil).List), varargs...)
}

// Modify mocks base method.
func (m *MockConfigSnapshotServiceClient) Modify(ctx context.Context, in *config_read.ModifyConfigRequest, opts ...grpc.CallOption) (*config_read.ModifyConfigResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Modify", varargs...)
	ret0, _ := ret[0].(*config_read.ModifyConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Modify indicates an expected call of Modify.
func (mr *MockConfigSnapshotServiceClientMockRecorder) Modify(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Modify", reflect.TypeOf((*MockConfigSnapshotServiceClient)(nil).Modify), varargs...)
}
